spring:
    datasource:
        url: jdbc:postgresql://netflix-user-pg12:5434/db_netflix_user
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: root
        initialization-mode: never
        tomcat:
          test-while-idle: true
          validation-query: SELECT 1
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        open-in-view: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
                default_schema: ${DATABASE_SCHEMA:public}
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
                    temp:
                        use_jdbc_metadata_defaults: false
    flyway:
        baseline-on-migrate: true
        locations:
            - classpath:db/migration